### ISSUE TITLE
wdio cucumber beginner 

### ISSUE THREAD

**Issue by sambhavidb** [jessedijkstra/wdio-cucumber-utilities#3]
Hi jessedijkstra,

I am a beginner to UI testing and want to explore wdio with cucumber framework for my application. I downloaded the code and tried to run it through command line using "wdio --spec ./test/features/select.feature" I am getting file not found exception. Not sure what is that that i am missing to run the project. Below is the cmd stack trace. Appreciate your input and help in advance

E:\wdio-cucumber-utilities-master>wdio --spec ./test/features/select.feature
C:\Users\anupsam\AppData\Roaming\npm\node_modules\webdriverio\build\lib\utils\Co
nfigParser.js:249
                    throw new Error(`spec file ${object.spec} not found`);
                    ^

Error: spec file ./test/features/select.feature not found
    at ConfigParser.merge (C:\Users\anupsam\AppData\Roaming\npm\node_modules\web
driverio\build\lib\utils\ConfigParser.js:249:27)
    at new Launcher (C:\Users\anupsam\AppData\Roaming\npm\node_modules\webdriver
io\build\lib\launcher.js:71:27)
    at launch (C:\Users\anupsam\AppData\Roaming\npm\node_modules\webdriverio\bui
ld\lib\cli.js:441:24)
    at Object.<anonymous> (C:\Users\anupsam\AppData\Roaming\npm\node_modules\web
driverio\build\lib\cli.js:459:5)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)

E:\wdio-cucumber-utilities-master>

**Comment by sambhavidb** [comment]
figured out how to run.
